### ISSUE TITLE
Animated 12th rotor

### ISSUE THREAD

**Issue by xX-GATT-Xx** [eccentricdevotion/TARDIS-Resource-Pack#4]
[Changes.zip](https://github.com/eccentricdevotion/TARDIS-Resource-Pack/files/5138996/Changes.zip)
 

i have made the 12th rotor spin like in the show. 

feel free to add it.

**Comment by eccentricdevotion** [comment]
Yep, the reason the original is not animated is I've already tried it and due to the restricted angles that you can rotate models in Java Minecraft, it just looks like the symbols are turning on the spot, rather than the rings of the rotor actually turning.

I think it looks bad, so I left the Twelfth rotor as un-animated.

Feel free to alter your personal resource pack as much as you want, but I won't be implementing this, unless Java model rotation changes.

**Comment by xX-GATT-Xx** [comment]
Aight.
